version: '3.3'
services:
  # postgres teste
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root      
    ports:
      - "5437:5432"
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql

