-- -- Database generated with pgModeler (PostgreSQL Database Modeler).
-- -- pgModeler version: 0.9.4
-- -- PostgreSQL version: 13.0
-- -- Project Site: pgmodeler.io
-- -- Model Author: Deskx
-- -- object: root | type: ROLE --
-- -- DROP ROLE IF EXISTS root;
-- CREATE ROLE root WITH 
-- 	SUPERUSER
-- 	CREATEROLE
-- 	LOGIN
-- 	ENCRYPTED PASSWORD '1010aa';
-- -- ddl-end --


-- -- Database creation must be performed outside a multi lined SQL file. 
-- -- These commands were put in this file only as a convenience.
-- -- 
-- -- object: root | type: DATABASE --
-- -- DROP DATABASE IF EXISTS root;
-- CREATE DATABASE root
-- 	ENCODING = 'UTF8'
-- 	LC_COLLATE = 'pt_BR'
-- 	LC_CTYPE = 'pt_BR';
-- -- ddl-end --


-- -- object: "Temporario" | type: SCHEMA --
-- -- DROP SCHEMA IF EXISTS "Temporario" CASCADE;
-- CREATE SCHEMA "Temporario";
-- -- ddl-end --
-- ALTER SCHEMA "Temporario" OWNER TO root;
-- -- ddl-end --

-- SET search_path TO pg_catalog,public,"Temporario";
-- ddl-end --

-- object: public.usuario | type: TABLE --
-- DROP TABLE IF EXISTS public.usuario CASCADE;
CREATE TABLE public.usuario (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	emailcorp character varying(200) NOT NULL,
	senha character varying(250) NOT NULL,
	CONSTRAINT usuario_pk PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.usuario OWNER TO root;
-- ddl-end --

